import matplotlib.pyplot as plt
import numpy as np
import os

# Set clean aesthetic styling
plt.style.use("seaborn-v0_8-whitegrid" if "seaborn-v0_8-whitegrid" in plt.style.available else "default")
plt.rcParams.update({
    "font.sans-serif": "DejaVu Sans",
    "axes.edgecolor": "#cccccc",
    "axes.linewidth": 0.8,
    "grid.color": "#eeeeee",
    "grid.linestyle": "--",
    "figure.autolayout": True
})

def plot_case_study(results_npz_path: str, title_prefix: str = "Case Study"):
    """
    Plots Feature Importance Bar Chart and Convergence Plots for SV and Order-2 Approximators.
    """
    # Load benchmarking data generated by the scripts
    data = np.load(results_npz_path, allow_pickle=True)
    
    feature_names = data["feature_names"]
    beta_exact = data["beta_exact"]
    sv_results = data["sv_results"]    # columns: [name, budget, max_err, mean_err, dt]
    int_results = data["int_results"]  # columns: [name, budget, max_err_1, max_err_2, dt]
    
    # -------------------------------------------------------------------------
    # FIGURE 1: Feature Contributions (Exact SV)
    # -------------------------------------------------------------------------
    fig1, ax1 = plt.subplots(figsize=(8, 4.5), dpi=150)
    
    # Sort features by absolute contribution
    sort_idx = np.argsort(np.abs(beta_exact))[::-1]
    sorted_features = feature_names[sort_idx]
    sorted_betas = beta_exact[sort_idx]
    
    colors = ["#2b5c8f" if val >= 0 else "#d95f02" for val in sorted_betas]
    bars = ax1.barh(sorted_features[::-1], sorted_betas[::-1], color=colors[::-1], edgecolor="none", height=0.65)
    
    ax1.axvline(0, color="black", linestyle="-", linewidth=0.8, alpha=0.7)
    ax1.set_xlabel("Exact Shapley Value Contribution ($\phi_i$)", fontsize=11, labelpad=8)
    ax1.set_title(f"{title_prefix}: Feature Contributions ($\phi_i$)", fontsize=13, fontweight="bold", pad=12)
    
    # Add numerical value annotations next to bars
    for bar in bars:
        width = bar.get_width()
        ha = "left" if width >= 0 else "right"
        offset = 0.05 if width >= 0 else -0.05
        ax1.text(width + offset, bar.get_y() + bar.get_height() / 2, f"{width:+.3f}",
                 va="center", ha=ha, fontsize=9, color="#333333")
    
    ax1.set_xlim(sorted_betas.min() * 1.25, sorted_betas.max() * 1.25)
    filename = f"{title_prefix.lower().replace(' ', '_')}_feature_importance.png"
    plt.savefig(os.path.join("plots", filename), bbox_inches="tight")

    plt.close(fig1)

    # -------------------------------------------------------------------------
    # FIGURE 2: Approximator Convergence vs Evaluation Budget
    # -------------------------------------------------------------------------
    fig2, (ax_sv, ax_int) = plt.subplots(1, 2, figsize=(12, 4.5), dpi=150)
    
    # --- Plot Order-1 SV Approximators Convergence ---
    unique_sv_algos = np.unique(sv_results[:, 0])
    for algo in unique_sv_algos:
        mask = sv_results[:, 0] == algo
        budgets = sv_results[mask, 1].astype(int)
        mean_errs = sv_results[mask, 3].astype(float)  # Mean Absolute Error
        ax_sv.plot(budgets, mean_errs, marker="o", linewidth=1.8, label=algo)
        
    ax_sv.set_yscale("log")
    ax_sv.set_xlabel("Evaluation Budget", fontsize=11)
    ax_sv.set_ylabel("Mean Absolute Error (MAE)", fontsize=11)
    ax_sv.set_title("Order-1 SV Approximators", fontsize=12, fontweight="bold")
    ax_sv.legend(frameon=True, facecolor="white", edgecolor="#e0e0e0", fontsize=9)

    # --- Plot Order-2 Interaction Approximators Convergence ---
    unique_int_algos = np.unique(int_results[:, 0])
    for algo in unique_int_algos:
        mask = int_results[:, 0] == algo
        budgets = int_results[mask, 1].astype(int)
        max_err_2 = int_results[mask, 3].astype(float)  # Max Error Order 2
        ax_int.plot(budgets, max_err_2, marker="s", linewidth=1.8, label=algo)
        
    ax_int.set_yscale("log")
    ax_int.set_xlabel("Evaluation Budget", fontsize=11)
    ax_int.set_ylabel("Max Absolute Error (Order 2)", fontsize=11)
    ax_int.set_title("Order-2 Interaction Approximators", fontsize=12, fontweight="bold")
    ax_int.legend(frameon=True, facecolor="white", edgecolor="#e0e0e0", fontsize=9)

    fig2.suptitle(f"{title_prefix}: Convergence vs. Sampling Budget", fontsize=14, fontweight="bold", y=1.02)
    plt.tight_layout()
    filename = f"{title_prefix.lower().replace(' ', '_')}_convergence.png"
    plt.savefig(os.path.join("plots", filename), bbox_inches="tight")
    plt.close(fig2)

    print(f"Plots successfully generated for {title_prefix}!")


# Generate plots for both case study datasets
if __name__ == "__main__":
    # Case Study 1: Charizard vs. Squirtle (from benchmark_pokemon.py)
    plot_case_study("benchmark_results.npz", title_prefix="Case Study 1 (Charizard vs Squirtle)")

    # Case Study 2: Skorupi vs. Wailord (from case_study_2.py)
    plot_case_study("benchmark_results_case2.npz", title_prefix="Case Study 2 (Skorupi vs Wailord)")